#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/graphics.h>
#include <wx/timer.h>
#include <wx/textfile.h>
#include <wx/anidecod.h>
#include <wx/filedlg.h>
#include <wx/dirdlg.h>
#include <wx/arrstr.h> 
#include <wx/image.h>
#include <wx/wfstream.h>
#include <wx/tokenzr.h>
#include <utility>
#include <algorithm>
#include <string>
#include "tools.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel2OnLeftDown( wxMouseEvent& event );
		void m_panel2OnLeftUp( wxMouseEvent& event );
		void m_panel2OnMotion( wxMouseEvent& event );
		void m_panel2OnPaint( wxPaintEvent& event );
		void m_panel2OnUpdateUI( wxUpdateUIEvent& event );
		void onTimelineClick( wxMouseEvent& event );
		void onTimelinePaint( wxPaintEvent& event );
		void onTimelineUpdate( wxUpdateUIEvent& event );
		void m_button1OnButtonClick( wxCommandEvent& event );
		void onEnableAnimationClicked( wxCommandEvent& event );
		void onSaveFrameConfigurationClicked( wxCommandEvent& event );
		void onStartAnimationButonClick( wxCommandEvent& event );
		void onStopButtonClick( wxCommandEvent& event );
		void onSaveToFileClicked( wxCommandEvent& event );
		void onLoadFromFileAnimationButton( wxCommandEvent& event );
		void onSaveAnimationToFileButtonClick( wxCommandEvent& event );
		void onTimerTick( wxTimerEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

	void draw(wxClientDC& dcClient);
	void drawForAnimation(wxClientDC& dcClient);
	void setSlidersPosition(std::vector<int> slidersValue);
	void saveSliders();
	void reset();
	void prepareAndStartAnimation();
	void animate();
	void saveAsGif();

private:
	std::vector<Line> _bones;
	std::vector<Circle> _joints;
	wxPoint start_point;
	double alpha = 0.0;
	double beta = 0.0;
	bool is_panel_clicked = false;
	bool is_enableAnimation_clicked = false;
	bool is_startAnimation_clicked = false;
	bool is_saveAnimationAsGif_clicked = false;
	int selectedFrame = 0;
	std::vector<std::vector<int>> animationVector;
	wxString filePath;
	std::vector<int> configurableFrames;
	std::vector<int> savedFrames;
	std::vector<wxPoint> linesPosition;
	std::vector<wxSlider*> sliders;
	std::vector<std::pair<int, std::vector<int>>> framesConfig;
	wxImageArray imageArray;
	FILE * m_pLogFile;
	int myFind(std::vector<std::pair<int, std::vector<int>>> whereToLookFor, int whatToLookFor);

};

#endif // __GUIMyFrame1__
