#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include "tools.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel2OnLeftDown( wxMouseEvent& event );
		void m_panel2OnLeftUp( wxMouseEvent& event );
		void m_panel2OnMotion( wxMouseEvent& event );
		void m_panel2OnPaint( wxPaintEvent& event );
		void m_panel2OnUpdateUI( wxUpdateUIEvent& event );
		void m_slider4OnScroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

		void draw(wxClientDC& dcClient);

	private:
		std::vector<Line> _bones;
		wxPoint start_point;
		double alpha = 0.0;
		double beta = 0.0;
		bool is_panel_clicked = false;


};

#endif // __GUIMyFrame1__
